---
- name: update web, nfs, db, and uat servers
  hosts: uat-webserver:nfs:db
  remote_user: ec2-user
  become: yes
  tasks:
    - name: delete wireshark
      package:
        name: wireshark
        state: absent
      ignore_errors: yes

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  tasks:
    - name: delete wireshark
      package:
        name: wireshark-qt
        state: absent
      ignore_errors: yes
