---
- hosts: nfs,webservers
  become: true
  tasks:
    - name: Installing and updating repos
      dnf:
        update_cache: yes
        state: present

    - name: Ensure chrony is installed
      dnf:
        name: chrony
        state: present

    - name: Ensure chrony is running 
      service:
        name: chronyd
        state: started
        enabled: yes

- hosts: db
  become: true
  tasks:
    - name: Installing and updating repos
      dnf:
        update_cache: yes
        state: present

    - name: Ensure chrony is installed
      dnf:
        name: chrony
        state: present

    - name: Ensure chrony is running 
      service:
        name: chronyd
        state: started
        enabled: yes

- hosts: lb
  become: true
  tasks:
    - name: Installing and updating repos
      apt:
        update_cache: yes
        state: present

    - name: Ensure ntp is installed
      apt:
        name: ntp
        state: present

    - name: Ensure ntp is running 
      service:
        name: ntp
        state: started
        enabled: yes
