[nfs]
172.31.28.73 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/npoweraws.pem

[webservers]
172.31.19.216 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/npoweraws.pem
172.31.24.145 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/npoweraws.pem

[db]
172.31.19.8 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/npoweraws.pem

[lb]
172.31.24.158 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/npoweraws.pem
