---
- name: update web, nfs, and db servers
  hosts: webservers:nfs:db
  remote_user: ec2-user
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
      become: yes

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update apt repo and ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
        update_cache: yes
      become: yes

